// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ui_project

#ifndef _UI_PROJECT_UI_H
#define _UI_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
extern lv_obj_t *ui_ScreenHome;
extern lv_obj_t *ui_PanelStatus;
extern lv_obj_t *ui_LabelBattery;
extern lv_obj_t *ui_LabelTime;
extern lv_obj_t *ui_ButtonApp;
extern lv_obj_t *ui_LabelApp;
extern lv_obj_t *ui_ButtonApp1;
extern lv_obj_t *ui_LabelApp1;
extern lv_obj_t *ui_ButtonApp2;
extern lv_obj_t *ui_LabelApp2;
extern lv_obj_t *ui_ButtonApp3;
extern lv_obj_t *ui_LabelApp3;
extern lv_obj_t *ui_LabelWifi;
extern lv_obj_t *ui_LabelGPS;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_Fixedasys14);
LV_FONT_DECLARE( ui_font_Fixedasys16);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
